services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - VERSION=docker
      - PLEX_CLAIM=claim-key
    volumes:
      - /m2/AppData/plex/config:/config
      - /m2/data/media:/data/media
      - /dev/shm:/transcode
      - /m2/AppData/plex/9999.ini:/usr/lib/plexmediaserver/Resources/Tuner/Shared/scanners/dvbc/transponders/9999.ini
    devices:
      - /dev/dri:/dev/dri
      #- /dev/dvb:/dev/dvb
      #- "/dev/dri/card0:/dev/dri/card0"
      #- "/dev/dri/renderD128:/dev/dri/renderD128"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /m2/AppData/sonarr/config:/config
      - /m2/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /m2/AppData/radarr/config:/config
      - /m2/data:/data
    ports:
      - 7878:7878
    healthcheck:
      test: curl -f http://localhost:7878/api/v3/health?apikey=apikey
      interval: 5m00s
      timeout: 10s
      retries: 2
      start_period: 30s
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /m2/AppData/sabnzbd/config:/config
      - /m2/data/usenet:/data/usenet
    ports:
      - 8282:8080
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /m2/AppData/lidarr/config:/config
      - /m2/data:/data
    ports:
      - 8686:8686
    restart: unless-stopped

